# 数据和模型保存设置
features_file: '/mnt/shareEEx/liuyang/code/PM_plus_experiment/data/IEMOCAP_multi/IEMOCAP_multi.pkl'
save_label: 'ser_model_run1' # 用于保存最佳模型的文件标签
repeat_idx: '0'

# 数据集划分
val_id: '1F' # 作为验证集的说话人ID
test_id: '1M' # 作为测试集的说话人ID

# 训练参数
training:
  num_epochs: 200
  early_stop: 4
  batch_size: 32
  lr: 0.0001

# GPU 设置
n_gpu: [0]

# 模型调优选项
tuning:
  oversampling: true
  pretrained: false
